### PR TITLE
fix ram issues

### LINKED ISSUE #17: Memory issue
The index.js file appears to be loading all of the files at once in for loops. This is very slow and inefficient, and can result in 100MB+ of files loaded into memory at once.

A solution could be either load and resolve the file path through a function instead, or to make fileData a function instead 
https://github.com/PrismarineJS/node-minecraft-packets/blob/master/index.js#L28

```diff
-fileData = require(path.join(DATA_PATH, gameType, version, sendType, packet, file))
+fileData = () => require(path.join(DATA_PATH, gameType, version, sendType, packet, file))
````

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -21,18 +21,16 @@ for (const gameType of gameTypes) {
...
-            fileData = require(path.join(DATA_PATH, gameType, version, sendType, packet, file))
-          } else if (file.endsWith('.raw')) {
-            fileData = fs.readFileSync(path.join(DATA_PATH, gameType, version, sendType, packet, file))
-          }
           if (!data[gameType][version][sendType][packet][index]) {
             data[gameType][version][sendType][packet][index] = {}
           }
-          data[gameType][version][sendType][packet][index][type] = fileData
+          if (type === 'json') {
+            Object.defineProperty(data[gameType][version][sendType][packet][index], type, { get () { return require(path.join(DATA_PATH, gameType, version, sendType, packet, file)) } })
```
Comment (extremeheat) [inline index.js]: Set `{ enumerable: true }` to make sure you can see and iterate the property, otherwise it remains invisible 
```js
{ enumerable: true, get () { return require(path.join(DATA_PATH, gameType, version, sendType, packet, file)) } }
```

Comment (u9g) [reply index.js]: done ty

**Comment by extremeheat** [comment]
lgtm

**Comment by extremeheat** [comment]
Small tip: instead of `data[gameType][version][sendType][packet][index]`, you can simplify this by defining a variable to an object.
```js
const entry = data[gameType][version][sendType][packet]
entry[index] = 2
```

In JS, all objects are references so you don't have to worry about a copy being made for them when assigning. Integers and strings aren't objects, so declaring a new variable *will* make a copy for them.

**Comment by u9g** [comment]
> Small tip: instead of `data[gameType][version][sendType][packet][index]`, you can simplify this by defining a variable to an object.
> 
> ```js
> const entry = data[gameType][version][sendType][packet]
> entry[index] = 2
> ```
> 
> In JS, all objects are references so you don't have to worry about a copy being made for them when assigning. Integers and strings aren't objects, so declaring a new variable _will_ make a copy for them.

thanks, added that

File: index.js [hunk 2]
```diff
@@ -21,18 +21,17 @@ for (const gameType of gameTypes) {
...
-          let fileData = null
           let [index, type] = file.split('.')
           index-- // decrement so the arrays wont have an empty slot (nmpd starts dumping at packet 1)
-          if (file.endsWith('.json')) {
-            fileData = require(path.join(DATA_PATH, gameType, version, sendType, packet, file))
-          } else if (file.endsWith('.raw')) {
-            fileData = fs.readFileSync(path.join(DATA_PATH, gameType, version, sendType, packet, file))
+          let entry = data[gameType][version][sendType][packet][index]
+          if (!entry) {
+            entry = {}
```
Comment (extremeheat) [inline index.js]: OK, should have said it clearer, but this won't work, it needs to be 
```js
let entry = data[gameType][version][sendType][packet]
if (!entry[index]) {
  entry[index] = {}
}
...
```

Just doing `entry = 3` without an object will just change the value of `entry`. Doing `entry.something = 3` will change the value of `something` *inside* of `entry` object

Comment (u9g) [reply index.js]: okay, I think I did what you are describing now

**Review by rom1504 — APPROVED** [review]
